language: php

sudo: required

php:
 - '7.0'

services:
 - docker
 
before_install: 
 - npm install -g grunt-cli
 - npm install
 - composer self-update
 - composer global require fxp/composer-asset-plugin -vvv
 
install:
 - composer validate
 - composer install

script:
 - php .scripts/translations.php somenergia-theme
 - php .scripts/translations.php somenergia_calendar
 - php .scripts/translations.php somenergia_drive
 - php .scripts/translations.php somenergia_index
 - php .scripts/translations.php somenergia-customization
 - .travis/build.sh
 - .travis/run.sh
 - grunt integration
 
after_script:
  - .travis/down.sh