language: php
php:
 - 5.5

services:
 - mysql

before_script:
 - mysql -e 'create database elgg;'
 - echo "USE mysql; UPDATE user SET password=PASSWORD('password') WHERE user='root'; FLUSH PRIVILEGES;" | mysql -u root
 - mkdir "${HOME}/elgg_data/"
 - php -f ./install/cli/travis_installer.php

script:
 - phpunit
 - php -f ./engine/tests/suite.php
