version: '2'
services:
  mysql:
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
    ports:
      - 3336:3306
  apache:
    build:
      context: .
      dockerfile: .docker/apache/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    volumes:
      - '~/.composer:/root/.composer'

    
